repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(src)
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.2.0
  hooks:
  # any R project
  - id: codemeta-description-updated
  - id: style-files
    args: [--style_pkg=styler, --style_fun=tidyverse_style]
  - id: lintr
    # args: [--warn_only]
    verbose: True
  - id: parsable-R
  - id: no-browser-statement
  - id: readme-rmd-rendered
  - id: roxygenize
  - id: use-tidy-description
  - id: deps-in-desc
