# To use:
#
#   $ micromamba create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate readcon_dev
#
name: readconr_dev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - pkg-config
  - arrow-cpp
  # For the R bindings
  - r-rcpp
  - r-devtools
  # For linting
  - r-styler
  - r-lintr
  - r-codemeta
  # Interactive R
  - radian
