name: Build R package and check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          # - {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      # GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Build and install
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH="$(pwd)/bbdir/subprojects/readCon/CppCore"
          Rscript -e 'devtools::install(".")'

      - name: Test run
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH="$(pwd)/bbdir/subprojects/readCon/CppCore"
          Rscript -e '
          library("readConR")
          aa <- readConR::readCon("test_data/cuh2.con")
          print(aa$prebox_header)
          print(aa$boxl)
          print(aa$angles)
          print(aa$postbox_header)
          print(aa$natm_types)
          print(aa$natms_per_type)
          print(aa$masses_per_type)
          print(aa$atom_data)
          '
